dist: trusty
sudo: false
language: ruby

jobs:
  include:
    - env: &adoc-latest ASCIIDOCTOR_VERSION=1.5.6.1
      rvm: 2.5
    - env: *adoc-latest
      rvm: 2.4
    - env: *adoc-latest
      rvm: 2.3
    - env: *adoc-latest
      rvm: 2.2
    - env: *adoc-latest
      rvm: 2.1
    - env: *adoc-latest
      # Using exact version as workaround for https://github.com/travis-ci/travis-ci/issues/8446.
      rvm: jruby-9.1.15.0
    - env: *adoc-latest
      rvm: ruby-head
    - env: *adoc-latest
      rvm: jruby-head

    - env: ASCIIDOCTOR_VERSION=1.5.6
      rvm: 2.3

    - env: ASCIIDOCTOR_VERSION="git:master"
      rvm: 2.5

  allow_failures:
    - env: *adoc-latest
      rvm: ruby-head
    - env: *adoc-latest
      rvm: jruby-head
    - env: ASCIIDOCTOR_VERSION="git:master"
      rvm: 2.5

env:
  global:
    secure: # CODACY_PROJECT_TOKEN

before_install:
  # Workaround for https://github.com/travis-ci/travis-ci/issues/8978.
  - gem update --system

script:
  - bundle exec rake spec
  - bundle exec rake rubocop

deploy:
  provider: rubygems
  api_key:
    secure: # RUBYGEMS KEY
  on:
    tags: true
    condition: ${TRAVIS_JOB_NUMBER#*.} = 1
