dist: trusty
sudo: false
language: ruby

jobs:
  include:
    - env: &adoc-latest ASCIIDOCTOR_VERSION=1.5.7
      rvm: &ruby-latest 2.5
    - env: *adoc-latest
      rvm: 2.4
    - env: *adoc-latest
      rvm: 2.3
    - env: *adoc-latest
      rvm: 2.2
    - env: *adoc-latest
      rvm: 2.1
    - env: *adoc-latest
      rvm: jruby-9.1
    - env: *adoc-latest
      rvm: ruby-head
    - env: *adoc-latest
      rvm: jruby-head

    - env: ASCIIDOCTOR_VERSION=1.5.6
      rvm: 2.4

    - env: ASCIIDOCTOR_VERSION=1.5.6.1
      rvm: 2.4

    - env: ASCIIDOCTOR_VERSION=1.5.6.2
      rvm: *ruby-latest

    - env: ASCIIDOCTOR_VERSION="git:master"
      rvm: *ruby-latest

  allow_failures:
    - env: *adoc-latest
      rvm: ruby-head
    - env: *adoc-latest
      rvm: jruby-head
    - env: ASCIIDOCTOR_VERSION="git:master"
      rvm: *ruby-latest

env:
  global:
    secure: "tXxL81YrHRaD90vTdIZ6eKWGQFWAYz9WKf64/xVNZxBiSTaiyabS6/k1XvVTkJ61x389Xcl9sMMFgtP5BCxVpfdOboD1R0v9dSqssPzxIOikw1XiKTJCSWPOoYy/Z8n/jR1U4AzVzhxCDyJrv4bd5NbxegrsV9aeIB5mGrPy1Hxz+IAAZOLTCEwiwFhHMpamn7+NDWMa7WFfBdCfkxO0VOa0hXmI0ogdB+kdRM2q+24bv8zs0OwUTNyd0Y0CtG02/Ad+f8C27mS2kqRpv64NRpiFh1a0RB8Fyj4Beax7VrhxJXYNIq53bBd+ue+DHgAciDpb3fV10sdjYuCmrWlYt9yZiAPBoqfvxL7ymV/AiSLdEBnMxXtK/BnYRmjLYb3kgt4yW9Eqnzy0xsARTSLqznfaV5Mm7nCJuwu5nIePeaL6CbBewu5R64kHn360nhJsLDlzLJnrXgLk0j9+V3LEmmxBn1lYChRZjq71I5D8bOPC7QLOd2Cgx+ObDiDEWSLal5F5DXc3wnbDsDJMsmDQjPt+erAIOv7b91iWQ6znn/75x0P0Rj2WunXwluW1rBqsBeDCsCRUO9qCeJJzr5XworZgSM5vH8Ge9z8C9YG73sCniWhhVZVkN33RWVLRw0MtXqiVP6OgPjLZqPJl4wtKux6EOCLSghb6wbD4ulaGRaw="  # CODACY_PROJECT_TOKEN

before_install:
  # Workaround for https://github.com/travis-ci/travis-ci/issues/8978.
  - gem update --system

script:
  - bundle exec rake spec
  - bundle exec rake rubocop
  - bundle exec rake build:js

deploy:
  - provider: rubygems
    api_key:
      secure: "hFbbR7X4VaRZSX7IIG8WnseceBzG3M++ClPOPskG3DDdC/USND8ecNKnfnjuOBAxU6OnrCoZUH9bpwo1cBtdXWZ2qU6PGr/m9K+RlIs7/5SyCLj7shs5IoSYwZm0mzyCiZv/7FptZmZvkG34r8PfisYwHPSAKQRBb9NomvvnEgo5MJEpdBUL/+78W3zC+KEaQj+oSDu9pB/F3jhDtcrTpvN9nD7j/brtqn44kVQh1Wweb5FHGLQnIGtvSzS0m6fnhY19ZCPvMpAGnvwN5N5Lz0WanZhnO4xT3C/lrA5FZyJfzUydNCwTDfZS6eoRhkreCt3YZjxOJot1IeONWk/0BFI8bnYAw8/5Uh4OTt5VKdoClJPAL/tSE8BY3tztDlDQuDN8DVTUML0k/2hNVxNElJzqcCiEwN4Q4BgS470OO/2aynGMjmxvIJn25HmfzotA32mdnk6NUEU+EmA8xu1fdLsrYELVzmGHQna/W5UVak70ZmNuVhJkHtAbaeGZgYB8y28IYlq16p1K2aB8b9Nas3wIM6RVpPm9RW/7DgQHI2z1bhrFVNYlFudXTBq/PDOwTvWpzQbFJUaWYBTFkkdtdxazz+72as2RoLSng4haQb9fnHXadIqtEmAmb2PdtdEY3leWbD/mQ2Ryh9J6gmM43DBkaB+aWCsWfYR0kHIGIZg="
    skip_cleanup: true
    on:
      tags: true
      condition: ${TRAVIS_JOB_NUMBER#*.} = 1
  - provider: npm
    email: jakub@jirutka.cz
    api_key:
      secure: "AT2dbBLlRDHwT5T34ccS5rwJrwZ+Mhw8P1TxZIuCak5igmeKzLNcFpWDxshVTnu/jC5cb2NpQDAxBmwue0cmMhTa1Ipgz83qsJGzDQ0nIH41ZEshBju5EEDtAz9hCrRA2ZAeq6eE3o1g5OUqido4IV9AKFGophsZSDkf4GihkBzDwK+/UQ+0im2njsHtuUDeSSOqQZc7eqKB58s8kfaBfqchYrtjcwD+LC6FYlNSHmff4UYrwClSgFPQEhqDbm/7UlXMF7bZrA5YNhtJn6oZdlBTpeX6d2AWMpXERMVtyg0tAdp9k8OkcWgOjCsjbvWp8ym8jGjy/kdSa7pz5/KR1yUdijesIFyqW0AkBNmMQbgGu7hky33F2RIdLhFO8DeyTySOazf4hKsJPIfp1tkjclPOKrakexhRNknL8QfBxBEV2R/d4aURcqIecgZpvXO9iJ2RzRR7aXgJGPTSTLp/+FFVS5935OvlOTUz+3GbeoMW2eMoCpRIYtF1GkIwM1NS+M5BovD/OiVE/8lW5iiYTTaKj0sib78aG6hiac1/yrSl2+jabcNdhEl4UgERIa/vSNeASQG3Sx9Dbulwd7Supr3H1udXkHjVy7BUfa4J2te26zBBN+WytAB/StclkFagcsnfPRKg072nm72j16QHC2/OFo/5noCOl+OqK45H5vI="  # fd4a......2d63
    skip_cleanup: true
    on:
      tags: true
      condition: ${TRAVIS_JOB_NUMBER#*.} = 1
